In [1]:
import pandas as pd
import numpy as np


## Numpy

* n-dimensional array: a collection of elements


In [2]:
a_py = [10,20,40,23, 2323, 121,4322]

In [3]:
type(a_py)

list

In [4]:
b_np = np.array([2, 34,12, 54,655])

In [5]:
type(b_np)

numpy.ndarray

In [6]:
a_py

[10, 20, 40, 23, 2323, 121, 4322]

In [7]:
b_np

array([  2,  34,  12,  54, 655])

### Q: muliply all the numbers by 10

In [8]:
arr=[]
for i in a_py:
  arr.append(i * 10)
arr

[100, 200, 400, 230, 23230, 1210, 43220]

In [9]:
list(map(lambda i: i*10, a_py))

[100, 200, 400, 230, 23230, 1210, 43220]

In [10]:
[i*10 for i in a_py]

[100, 200, 400, 230, 23230, 1210, 43220]

In [13]:
b_np * 10
# much better performance an smaller memory footprint

array([  20,  340,  120,  540, 6550])

### trade off : numpy arrays contain only one data type

In [21]:
c_np = np.array([1,3.,4])
#implicit upcasting : 

In [22]:
c_np

array([1., 3., 4.])

In [23]:
c_np.dtype

dtype('float64')

In [24]:
b_np.dtype

dtype('int64')